import streamlit as st
import os
if 'page' not in st.session_state:
    st.session_state.page='home'
st.set_page_config(layout='wide',page_title='FX AMBUSHERS')
if os.path.exists('logo.png'):
    st.image('logo.png')
else:
    st.markdown('<div style="text-align:center;padding:12px;background:#000;border:1px solid gold;border-radius:14px"><h2 style="color:gold">Mr SA Dlamini</h2><h1 style="color:gold">FX AMBUSHERS</h1><p style="color:gold">Premium Trading</p></div>',unsafe_allow_html=True)

def badge(t):
    c='#ff3355' if 'Bear' in t else '#00ff88' if 'Bull' in t else '#ffcc00'
    return '<span style="background:'+c+'22;color:'+c+';border:1px solid '+c+';padding:4px 8px;border-radius:8px;font-size:12px">'+t+'</span>'
def gcard(t,s,sub):
    c='#00ff88' if s>=2 else '#ff3355' if s<=-2 else '#ffcc00'
    b='NEUTRAL'
    if s>=6: b='Very Bullish'
    elif s>=2: b='Bullish'
    elif s<=-6: b='Very Bearish'
    elif s<=-2: b='Bearish'
    return '<div style="background:#0e0e0e;border-radius:18px;padding:14px;margin:6px;border-left:6px solid '+c+'"><b style="color:#fff">'+t+'</b><br><span style="color:'+c+';font-size:20px">'+str(s)+' '+b+'</span><br><span style="color:#888;font-size:11px">'+sub+'</span></div>'

# ALL PAIRS - 18 PAIRS - EACH DIFFERENT
def mk(a,te,se,ma,techL,cot,cotLS,why):
    return {'a':a,'te':te,'se':se,'ma':ma,'techL':techL,'4h':'Bearish' if te<0 else 'Bullish','seas':'Neutral','cot':cot,'cotLS':cotLS,'gdp':'Neutral 0.6 vs 0.6','pmiM':'Bearish 48.5 vs 49.0','pmiS':'Bullish 53.2 vs 52.8','retail':'Bearish -0.2 vs 0.3','conf':'Neutral 102 vs 103','cpi':'Neutral 2.8 vs 3.0','ppi':'Neutral 1.5 vs 1.6','pce':'Neutral 2.5 vs 2.5','yld':'Bearish yield up','nfp':'Neutral 140k vs 145k','unemp':'Neutral 4.3 vs 4.3','jobless':'Bullish 195k vs 200k','adp':'Bearish 25k vs 35k','jolts':'Neutral 7.3M vs 7.3M','why':why}

FULL={
 'DXY':{'a':7,'te':7,'se':6,'ma':6,'techL':'Very Bullish','4h':'Very Bullish','seas':'Bullish','cot':'Very Bullish Long 88.95 Short 11.05','cotLS':'Bullish','gdp':'Bullish 2.8 vs 2.5','pmiM':'Bullish 52.1 vs 51.0','pmiS':'Bullish 55.2 vs 54.0','retail':'Bullish 0.4 vs 0.1','conf':'Very Bullish 105 vs 102','cpi':'Bullish 3.6 vs 3.4','ppi':'Bullish 4.9 vs 4.7','pce':'Bullish 3.5 vs 3.3','yld':'Very Bullish 2Y rising','nfp':'Very Bullish 250k vs 150k','unemp':'Bullish 3.9 vs 4.1','jobless':'Very Bullish 190k vs 205k','adp':'Very Bullish 100k vs 47k','jolts':'Very Bullish 8.5M vs 7.33M','why':'DXY KING: All Very Bullish + COT 88 Long = BUY DXY'},
 'EURUSD':{'a':-7,'te':-7,'se':-5,'ma':-2,'techL':'Very Bearish','4h':'Bearish','seas':'Very Bearish','cot':'Bearish Long 29 Short 71','cotLS':'Bearish','gdp':'Bearish 0.3 vs 0.4','pmiM':'Bearish 49.2 vs 50.1','pmiS':'Neutral 52.1 vs 52.3','retail':'Bearish -0.4 vs 0.2','conf':'Bearish 96.1 vs 97.2','cpi':'Bearish 2.1 vs 2.3','ppi':'Neutral 1.8 vs 1.9','pce':'Bearish 2.0 vs 2.2','yld':'Very Bearish yield rising','nfp':'Bullish 180k vs 150k','unemp':'Bullish 6.5 vs 6.6','jobless':'Bearish 220k vs 210k','adp':'Bearish 30k vs 50k','jolts':'Bearish 7.1M vs 7.4M','why':'EURUSD AMBUSH: DXY King + EUR 71 Short = SELL'},
 'GBPUSD':{'a':-6,'te':-6,'se':-4,'ma':-1,'techL':'Bearish','4h':'Bearish','seas':'Neutral','cot':'Bearish Long 35 Short 65','cotLS':'Neutral','gdp':'Neutral 0.6 vs 0.6','pmiM':'Bearish 48.5 vs 49.0','pmiS':'Bullish 53.2 vs 52.8','retail':'Bearish -0.2 vs 0.3','conf':'Neutral 102 vs 103','cpi':'Bearish 2.8 vs 3.0','ppi':'Neutral 1.5 vs 1.6','pce':'Neutral 2.5 vs 2.5','yld':'Bearish yield up','nfp':'Neutral 140k vs 145k','unemp':'Neutral 4.3 vs 4.3','jobless':'Bullish 195k vs 200k','adp':'Bearish 25k vs 35k','jolts':'Neutral 7.3M vs 7.3M','why':'GBPUSD AMBUSH: DXY strength + GBP weak PMI = SELL'},
 'USDJPY':{'a':7,'te':6,'se':4,'ma':7,'techL':'Very Bullish','4h':'Bullish','seas':'Bullish','cot':'Very Bullish Long 82 Short 18','cotLS':'Bullish','gdp':'Very Bullish 1.9 vs 1.2','pmiM':'Bullish 51.2 vs 50.5','pmiS':'Very Bullish 54.8 vs 53.1','retail':'Very Bullish 1.2 vs 0.5','conf':'Bullish 98 vs 96','cpi':'Very Bullish 3.2 vs 2.9','ppi':'Very Bullish 3.8 vs 3.2','pce':'Bullish 3.1 vs 2.9','yld':'Very Bullish yield up BOJ dovish','nfp':'Very Bullish 220k vs 150k','unemp':'Bullish 3.8 vs 4.0','jobless':'Very Bullish 180k vs 205k','adp':'Very Bullish 90k vs 47k','jolts':'Very Bullish 8.1M vs 7.33M','why':'USDJPY AMBUSH: DXY Very Bullish + JPY weak = BUY'},
 'AUDUSD':{'a':-7,'te':-7,'se':-6,'ma':-2,'techL':'Very Bearish','4h':'Bearish','seas':'Bearish','cot':'Bearish Long 28 Short 72','cotLS':'Bearish','gdp':'Bearish 0.2 vs 0.4','pmiM':'Bearish 47.8 vs 49.0','pmiS':'Neutral 51.0 vs 51.5','retail':'Bearish -0.5 vs 0.1','conf':'Bearish 85 vs 90','cpi':'Bearish 2.5 vs 2.8','ppi':'Bearish 1.2 vs 1.5','pce':'Neutral 2.4 vs 2.5','yld':'Bearish','nfp':'Neutral','unemp':'Bearish 4.5 vs 4.2','jobless':'Bearish','adp':'Bearish','jolts':'Bearish','why':'AUDUSD AMBUSH: DXY strong + China weak + COT 72 Short = SELL'},
 'USDCHF':{'a':6,'te':5,'se':3,'ma':5,'techL':'Bullish','4h':'Bullish','seas':'Bullish','cot':'Bullish Long 68 Short 32','cotLS':'Bullish','gdp':'Bullish 1.2 vs 0.8','pmiM':'Bullish 52.0 vs 51.0','pmiS':'Bullish 54.0 vs 53.0','retail':'Bullish 0.3 vs 0.1','conf':'Bullish 99 vs 97','cpi':'Bullish 2.0 vs 1.8','ppi':'Bullish 2.2 vs 2.0','pce':'Bullish','yld':'Bullish','nfp':'Bullish','unemp':'Bullish','jobless':'Bullish','adp':'Bullish','jolts':'Bullish','why':'USDCHF AMBUSH: DXY Bull + CHF safe sell = BUY'},
 'USDCAD':{'a':6,'te':6,'se':4,'ma':4,'techL':'Bullish','4h':'Bullish','seas':'Very Bullish','cot':'Bullish Long 72 Short 28','cotLS':'Very Bullish','gdp':'Bullish 1.5 vs 1.0','pmiM':'Neutral 50.2 vs 50.5','pmiS':'Bullish 53.5 vs 52.8','retail':'Bullish 0.5 vs 0.2','conf':'Bullish 100 vs 98','cpi':'Bullish 3.0 vs 2.8','ppi':'Bullish 2.5 vs 2.2','pce':'Bullish','yld':'Bullish','nfp':'Bullish','unemp':'Neutral','jobless':'Bullish','adp':'Bullish','jolts':'Bullish','why':'USDCAD AMBUSH: DXY Bull + Oil weak = BUY USDCAD'},
 'NZDUSD':{'a':-6,'te':-6,'se':-5,'ma':-2,'techL':'Bearish','4h':'Bearish','seas':'Bearish','cot':'Bearish Long 32 Short 68','cotLS':'Bearish','gdp':'Bearish 0.1 vs 0.3','pmiM':'Bearish 47.0 vs 48.5','pmiS':'Bearish 50.1 vs 51.0','retail':'Bearish -0.3 vs 0.2','conf':'Bearish 88 vs 92','cpi':'Bearish','ppi':'Bearish','pce':'Neutral','yld':'Bearish','nfp':'Neutral','unemp':'Bearish','jobless':'Neutral','adp':'Bearish','jolts':'Bearish','why':'NZDUSD AMBUSH: DXY strong + NZD weak = SELL'},
 'GOLD':{'a':2,'te':-3,'se':1,'ma':4,'techL':'Very Bearish','4h':'Bearish','seas':'Bearish','cot':'Bullish Long 25 Short 75','cotLS':'Bearish','gdp':'Neutral 1.5 vs 1.5','pmiM':'Bullish 54.6 vs 55.2','pmiS':'Bearish 55.4 vs 54.1','retail':'Bullish -0.6 vs 0.1','conf':'Bullish 89.4 vs 90.3','cpi':'Neutral 3.4 vs 3.4','ppi':'Bullish 4.70 vs 4.90','pce':'Neutral 3.3 vs 3.3','yld':'Bearish yield rising','nfp':'Bearish 162k vs 55k','unemp':'Neutral 4.1 vs 4.1','jobless':'Bullish 206k vs 205k','adp':'Bullish 38k vs 47k','jolts':'Bullish 7.27M vs 7.33M','why':'GOLD AMBUSH: Tech Very Bearish + Retail 75 Long trapped = SELL'},
 'SILVER':{'a':-2,'te':-4,'se':0,'ma':3,'techL':'Bearish','4h':'Bearish','seas':'Neutral','cot':'Bearish Long 40 Short 60','cotLS':'Neutral','gdp':'Neutral','pmiM':'Bullish 54.6 vs 55.2','pmiS':'Bearish 55.4 vs 54.1','retail':'Bullish','conf':'Bullish','cpi':'Neutral','ppi':'Bullish','pce':'Neutral','yld':'Bearish','nfp':'Bearish','unemp':'Neutral','jobless':'Bullish','adp':'Bullish','jolts':'Bullish','why':'SILVER AMBUSH: Gold trap + Tech
